# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('multi_images', models.ImageField(blank=True, height_field='multi_height_image', null=True, upload_to=b'', width_field='multi_width_image')),
                ('multi_height_image', models.IntegerField(default=0)),
                ('multi_width_image', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desciption', models.TextField()),
                ('album_photo', models.ImageField(height_field='album_height_image', upload_to=b'', width_field='album_width_image')),
                ('album_height_image', models.IntegerField(default=0)),
                ('album_width_image', models.IntegerField(default=0)),
                ('timestam', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
