# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_quote', models.TextField()),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('maritialStatus', models.CharField(max_length=10)),
                ('citizenship', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=120)),
                ('timestam', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
