# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='width_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, height_field='height_image', null=True, upload_to=b'', width_field='width_image'),
        ),
    ]
