# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_date', models.DateField(verbose_name='%Y')),
                ('university', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('division', models.IntegerField()),
                ('timestam', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
