# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_auto_20180216_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='pass_date',
        ),
    ]
