# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0003_remove_qualification_pass_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='division',
            field=models.FloatField(),
        ),
    ]
