# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0004_auto_20180216_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='division',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
